# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/agent_types.msgpack.gz (13 entries)

class SDE::AgentType < Dry::Struct
  transform_keys(&:to_sym)

  attribute :name, SDE::Types::String
end
