# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/agents_in_space.msgpack.gz (360 entries)

module SDE
  class AgentsInSpace < Dry::Struct
    transform_keys(&:to_sym)

    attribute :dungeonID, SDE::Types::Integer
    attribute :solarSystemID, SDE::Types::Integer
    attribute :spawnPointID, SDE::Types::Integer
    attribute :typeID, SDE::Types::Integer
  end
end
