# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/ancestries.msgpack.gz (43 entries)

module SDE
  class Ancestry < Dry::Struct
    transform_keys(&:to_sym)

    attribute :bloodlineID, SDE::Types::Integer
    attribute :charisma, SDE::Types::Integer
    attribute :description, SDE::Types::LocalizedString
    attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :intelligence, SDE::Types::Integer
    attribute :memory, SDE::Types::Integer
    attribute :name, SDE::Types::LocalizedString
    attribute :perception, SDE::Types::Integer
    attribute :shortDescription, SDE::Types::String.optional.meta(omittable: true)
    attribute :willpower, SDE::Types::Integer
  end
end
