# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/bloodlines.msgpack.gz (18 entries)

module SDE
  class Bloodline < Dry::Struct
    transform_keys(&:to_sym)

    attribute :charisma, SDE::Types::Integer
    attribute :corporationID, SDE::Types::Integer
    attribute :description, SDE::Types::LocalizedString
    attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :intelligence, SDE::Types::Integer
    attribute :memory, SDE::Types::Integer
    attribute :name, SDE::Types::LocalizedString
    attribute :perception, SDE::Types::Integer
    attribute :raceID, SDE::Types::Integer
    attribute :willpower, SDE::Types::Integer
  end
end
