# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/blueprints.msgpack.gz (5059 entries)

class SDE::Blueprint < Dry::Struct
  transform_keys(&:to_sym)

  attribute :activities, SDE::Types::Hash
  attribute :blueprintTypeID, SDE::Types::Integer
  attribute :maxProductionLimit, SDE::Types::Integer
end
