# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/categories.msgpack.gz (48 entries)

class SDE::Category < Dry::Struct
  transform_keys(&:to_sym)

  attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, SDE::Types::LocalizedString
  attribute :published, SDE::Types::Bool
end
