# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/certificates.msgpack.gz (136 entries)

class SDE::Certificate < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, SDE::Types::LocalizedString
  attribute :groupID, SDE::Types::Integer
  attribute :name, SDE::Types::LocalizedString
  attribute :recommendedFor, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
  attribute :skillTypes, SDE::Types::Hash
end
