# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/character_attributes.msgpack.gz (5 entries)

class SDE::CharacterAttribute < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, SDE::Types::String
  attribute :iconID, SDE::Types::Integer
  attribute :name, SDE::Types::LocalizedString
  attribute :notes, SDE::Types::String
  attribute :shortDescription, SDE::Types::String
end
