# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/clone_grades.msgpack.gz (4 entries)

module SDE
  class CloneGrade < Dry::Struct
    transform_keys(&:to_sym)

    attribute :name, SDE::Types::String
    attribute :skills, SDE::Types::Array.of(SDE::Types::Hash)
  end
end
