# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/compressible_types.msgpack.gz (206 entries)

class SDE::CompressibleType < Dry::Struct
  transform_keys(&:to_sym)

  attribute :compressedTypeID, SDE::Types::Integer
end
