# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/contraband_types.msgpack.gz (8 entries)

class SDE::ContrabandType < Dry::Struct
  transform_keys(&:to_sym)

  attribute :factions, SDE::Types::Hash
end
