# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/corporation_activities.msgpack.gz (20 entries)

class SDE::CorporationActivity < Dry::Struct
  transform_keys(&:to_sym)

  attribute :name, SDE::Types::LocalizedString
end
