# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dbuff_collections.msgpack.gz (206 entries)

class SDE::DbuffCollection < Dry::Struct
  transform_keys(&:to_sym)

  attribute :aggregateMode, SDE::Types::String
  attribute :developerDescription, SDE::Types::String
  attribute :displayName, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :itemModifiers, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  attribute :locationGroupModifiers, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  attribute :locationModifiers, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  attribute :locationRequiredSkillModifiers, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  attribute :operationName, SDE::Types::String
  attribute :showOutputValueInUI, SDE::Types::String
end
