# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogma_attribute_categories.msgpack.gz (37 entries)

class SDE::DogmaAttributeCategory < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, SDE::Types::String.optional.meta(omittable: true)
  attribute :name, SDE::Types::String
end
