# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogma_effects.msgpack.gz (3354 entries)

class SDE::DogmaEffect < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :disallowAutoRepeat, SDE::Types::Bool
  attribute :dischargeAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :displayName, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :distribution, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :durationAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :effectCategoryID, SDE::Types::Integer
  attribute :electronicChance, SDE::Types::Bool
  attribute :falloffAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :fittingUsageChanceAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :guid, SDE::Types::String.optional.meta(omittable: true)
  attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :isAssistance, SDE::Types::Bool
  attribute :isOffensive, SDE::Types::Bool
  attribute :isWarpSafe, SDE::Types::Bool
  attribute :modifierInfo, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  attribute :name, SDE::Types::String
  attribute :npcActivationChanceAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :npcUsageChanceAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :propulsionChance, SDE::Types::Bool
  attribute :published, SDE::Types::Bool
  attribute :rangeAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :rangeChance, SDE::Types::Bool
  attribute :resistanceAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :trackingSpeedAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
end
