# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogma_units.msgpack.gz (60 entries)

class SDE::DogmaUnit < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :displayName, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :name, SDE::Types::String
end
