# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogma_attributes.msgpack.gz (2822 entries)

module SDE
  class DogmaAttribute < Dry::Struct
    transform_keys(&:to_sym)

    attribute :attributeCategoryID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :chargeRechargeTimeID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :dataType, SDE::Types::Integer
    attribute :defaultValue, SDE::Types::Float
    attribute :description, SDE::Types::String.optional.meta(omittable: true)
    attribute :displayName, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :displayWhenZero, SDE::Types::Bool
    attribute :highIsGood, SDE::Types::Bool
    attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :maxAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :minAttributeID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, SDE::Types::String
    attribute :published, SDE::Types::Bool
    attribute :stackable, SDE::Types::Bool
    attribute :tooltipDescription, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :tooltipTitle, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :unitID, SDE::Types::Integer.optional.meta(omittable: true)
  end
end
