# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dynamic_item_attributes.msgpack.gz (413 entries)

class SDE::DynamicItemAttribute < Dry::Struct
  transform_keys(&:to_sym)

  attribute :attributeIDs, SDE::Types::Hash
  attribute :inputOutputMapping, SDE::Types::Array.of(SDE::Types::Hash)
end
