# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/factions.msgpack.gz (27 entries)

module SDE
  class Faction < Dry::Struct
    transform_keys(&:to_sym)

    attribute :corporationID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :description, SDE::Types::LocalizedString
    attribute :flatLogo, SDE::Types::String.optional.meta(omittable: true)
    attribute :flatLogoWithName, SDE::Types::String.optional.meta(omittable: true)
    attribute :iconID, SDE::Types::Integer
    attribute :memberRaces, SDE::Types::Array.of(SDE::Types::Integer)
    attribute :militiaCorporationID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, SDE::Types::LocalizedString
    attribute :shortDescription, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :sizeFactor, SDE::Types::Float
    attribute :solarSystemID, SDE::Types::Integer
    attribute :uniqueName, SDE::Types::Bool
  end
end
