# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/freelance_job_schemas.msgpack.gz (1 entries)

module SDE
  class FreelanceJobSchema < Dry::Struct
    transform_keys(&:to_sym)

    attribute :BoostShield, SDE::Types::Hash
    attribute :CaptureFWComplex, SDE::Types::Hash
    attribute :DamageShip, SDE::Types::Hash
    attribute :DefendFWComplex, SDE::Types::Hash
    attribute :DeliverItem, SDE::Types::Hash
    attribute :KillCapsuleer, SDE::Types::Hash
    attribute :KillNPC, SDE::Types::Hash
    attribute :MineOre, SDE::Types::Hash
    attribute :RepairArmor, SDE::Types::Hash
    attribute :ShipInsurance, SDE::Types::Hash
  end
end
