# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/graphics.msgpack.gz (5549 entries)

module SDE
  class Graphic < Dry::Struct
    transform_keys(&:to_sym)

    attribute :graphicFile, SDE::Types::String.optional.meta(omittable: true)
    attribute :iconFolder, SDE::Types::String.optional.meta(omittable: true)
    attribute :sofFactionName, SDE::Types::String.optional.meta(omittable: true)
    attribute :sofHullName, SDE::Types::String.optional.meta(omittable: true)
    attribute :sofLayout, SDE::Types::Array.of(SDE::Types::String).optional.meta(omittable: true)
    attribute :sofMaterialSetID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :sofRaceName, SDE::Types::String.optional.meta(omittable: true)
  end
end
