# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/groups.msgpack.gz (1578 entries)

class SDE::Group < Dry::Struct
  transform_keys(&:to_sym)

  attribute :anchorable, SDE::Types::Bool
  attribute :anchored, SDE::Types::Bool
  attribute :categoryID, SDE::Types::Integer
  attribute :fittableNonSingleton, SDE::Types::Bool
  attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, SDE::Types::LocalizedString
  attribute :published, SDE::Types::Bool
  attribute :useBasePrice, SDE::Types::Bool
end
