# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/icons.msgpack.gz (4452 entries)

module SDE
  class Icon < Dry::Struct
    transform_keys(&:to_sym)

    attribute :iconFile, SDE::Types::String
  end
end
