# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/landmarks.msgpack.gz (45 entries)

module SDE
  class Landmark < Dry::Struct
    transform_keys(&:to_sym)

    attribute :description, SDE::Types::LocalizedString
    attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :locationID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, SDE::Types::LocalizedString
    attribute :position, SDE::Types::Hash
  end
end
