# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_planets.msgpack.gz (67961 entries)

class SDE::MapPlanet < Dry::Struct
  transform_keys(&:to_sym)

  attribute :asteroidBeltIDs, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
  attribute :attributes, SDE::Types::Hash
  attribute :celestialIndex, SDE::Types::Integer
  attribute :moonIDs, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
  attribute :npcStationIDs, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
  attribute :orbitID, SDE::Types::Integer
  attribute :position, SDE::Types::Hash
  attribute :radius, SDE::Types::Integer
  attribute :solarSystemID, SDE::Types::Integer
  attribute :statistics, SDE::Types::Hash
  attribute :typeID, SDE::Types::Integer
  attribute :uniqueName, SDE::Types::LocalizedString.optional.meta(omittable: true)
end
