# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_constellations.msgpack.gz (1175 entries)

class SDE::MapConstellation < Dry::Struct
  transform_keys(&:to_sym)

  attribute :factionID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, SDE::Types::LocalizedString
  attribute :position, SDE::Types::Hash
  attribute :regionID, SDE::Types::Integer
  attribute :solarSystemIDs, SDE::Types::Array.of(SDE::Types::Integer)
  attribute :wormholeClassID, SDE::Types::Integer.optional.meta(omittable: true)
end
