# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_asteroid_belts.msgpack.gz (40928 entries)

module SDE
  class MapAsteroidBelt < Dry::Struct
    transform_keys(&:to_sym)

    attribute :celestialIndex, SDE::Types::Integer
    attribute :orbitID, SDE::Types::Integer
    attribute :orbitIndex, SDE::Types::Integer
    attribute :position, SDE::Types::Hash
    attribute :radius, SDE::Types::Float.optional.meta(omittable: true)
    attribute :solarSystemID, SDE::Types::Integer
    attribute :statistics, SDE::Types::Hash.optional.meta(omittable: true)
    attribute :typeID, SDE::Types::Integer
    attribute :uniqueName, SDE::Types::LocalizedString.optional.meta(omittable: true)
  end
end
