# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_moons.msgpack.gz (342170 entries)

class SDE::MapMoon < Dry::Struct
  transform_keys(&:to_sym)

  attribute :attributes, SDE::Types::Hash
  attribute :celestialIndex, SDE::Types::Integer
  attribute :npcStationIDs, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
  attribute :orbitID, SDE::Types::Integer
  attribute :orbitIndex, SDE::Types::Integer
  attribute :position, SDE::Types::Hash
  attribute :radius, SDE::Types::Float
  attribute :solarSystemID, SDE::Types::Integer
  attribute :statistics, SDE::Types::Hash.optional.meta(omittable: true)
  attribute :typeID, SDE::Types::Integer
  attribute :uniqueName, SDE::Types::LocalizedString.optional.meta(omittable: true)
end
