# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_solar_systems.msgpack.gz (8437 entries)

module SDE
  class MapSolarSystem < Dry::Struct
    transform_keys(&:to_sym)

    attribute :border, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :constellationID, SDE::Types::Integer
    attribute :corridor, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :disallowedAnchorCategories, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
    attribute :disallowedAnchorGroups, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
    attribute :factionID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :fringe, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :hub, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :international, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :luminosity, SDE::Types::Float.optional.meta(omittable: true)
    attribute :name, SDE::Types::LocalizedString
    attribute :planetIDs, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
    attribute :position, SDE::Types::Hash
    attribute :position2D, SDE::Types::Hash.optional.meta(omittable: true)
    attribute :radius, SDE::Types::Float
    attribute :regionID, SDE::Types::Integer
    attribute :regional, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :securityClass, SDE::Types::String.optional.meta(omittable: true)
    attribute :securityStatus, SDE::Types::Float
    attribute :starID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :stargateIDs, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
    attribute :visualEffect, SDE::Types::String.optional.meta(omittable: true)
    attribute :wormholeClassID, SDE::Types::Integer.optional.meta(omittable: true)
  end
end
