# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_stargates.msgpack.gz (13776 entries)

class SDE::MapStargate < Dry::Struct
  transform_keys(&:to_sym)

  attribute :destination, SDE::Types::Hash
  attribute :position, SDE::Types::Hash
  attribute :solarSystemID, SDE::Types::Integer
  attribute :typeID, SDE::Types::Integer
end
