# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_stars.msgpack.gz (8036 entries)

class SDE::MapStar < Dry::Struct
  transform_keys(&:to_sym)

  attribute :radius, SDE::Types::Integer
  attribute :solarSystemID, SDE::Types::Integer
  attribute :statistics, SDE::Types::Hash
  attribute :typeID, SDE::Types::Integer
end
