# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_regions.msgpack.gz (113 entries)

module SDE
  class MapRegion < Dry::Struct
    transform_keys(&:to_sym)

    attribute :constellationIDs, SDE::Types::Array.of(SDE::Types::Integer)
    attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :factionID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, SDE::Types::LocalizedString
    attribute :nebulaID, SDE::Types::Integer
    attribute :position, SDE::Types::Hash
    attribute :wormholeClassID, SDE::Types::Integer.optional.meta(omittable: true)
  end
end
