# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/market_groups.msgpack.gz (2092 entries)

class SDE::MarketGroup < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :hasTypes, SDE::Types::Bool
  attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, SDE::Types::LocalizedString
  attribute :parentGroupID, SDE::Types::Integer.optional.meta(omittable: true)
end
