# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/masteries.msgpack.gz (468 entries)

class SDE::Mastery < Dry::Struct
  transform_keys(&:to_sym)

  attribute :"0", SDE::Types::Array.of(SDE::Types::Integer)
  attribute :"1", SDE::Types::Array.of(SDE::Types::Integer)
  attribute :"2", SDE::Types::Array.of(SDE::Types::Integer)
  attribute :"3", SDE::Types::Array.of(SDE::Types::Integer)
  attribute :"4", SDE::Types::Array.of(SDE::Types::Integer)
end
