# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/meta_groups.msgpack.gz (13 entries)

class SDE::MetaGroup < Dry::Struct
  transform_keys(&:to_sym)

  attribute :color, SDE::Types::Hash.optional.meta(omittable: true)
  attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :iconSuffix, SDE::Types::String.optional.meta(omittable: true)
  attribute :name, SDE::Types::LocalizedString
end
