# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npc_corporations.msgpack.gz (283 entries)

module SDE
  class NpcCorporation < Dry::Struct
    transform_keys(&:to_sym)

    attribute :allowedMemberRaces, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
    attribute :ceoID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :corporationTrades, SDE::Types::Hash.optional.meta(omittable: true)
    attribute :deleted, SDE::Types::Bool
    attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :divisions, SDE::Types::Hash.optional.meta(omittable: true)
    attribute :enemyID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :exchangeRates, SDE::Types::Hash.optional.meta(omittable: true)
    attribute :extent, SDE::Types::String
    attribute :factionID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :friendID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :hasPlayerPersonnelManager, SDE::Types::Bool
    attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :initialPrice, SDE::Types::Integer
    attribute :investors, SDE::Types::Hash.optional.meta(omittable: true)
    attribute :lpOfferTables, SDE::Types::Array.of(SDE::Types::Integer).optional.meta(omittable: true)
    attribute :mainActivityID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :memberLimit, SDE::Types::Integer
    attribute :minSecurity, SDE::Types::Float
    attribute :minimumJoinStanding, SDE::Types::Integer
    attribute :name, SDE::Types::LocalizedString
    attribute :raceID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :secondaryActivityID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :sendCharTerminationMessage, SDE::Types::Bool
    attribute :shares, SDE::Types::Integer
    attribute :size, SDE::Types::String
    attribute :sizeFactor, SDE::Types::Float.optional.meta(omittable: true)
    attribute :solarSystemID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :stationID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :taxRate, SDE::Types::Float
    attribute :tickerName, SDE::Types::String
    attribute :uniqueName, SDE::Types::Bool
  end
end
