# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npc_corporation_divisions.msgpack.gz (10 entries)

class SDE::NpcCorporationDivision < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :displayName, SDE::Types::String.optional.meta(omittable: true)
  attribute :internalName, SDE::Types::String
  attribute :leaderTypeName, SDE::Types::LocalizedString
  attribute :name, SDE::Types::LocalizedString
end
