# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npc_stations.msgpack.gz (5154 entries)

module SDE
  class NpcStation < Dry::Struct
    transform_keys(&:to_sym)

    attribute :celestialIndex, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :operationID, SDE::Types::Integer
    attribute :orbitID, SDE::Types::Integer
    attribute :orbitIndex, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :ownerID, SDE::Types::Integer
    attribute :position, SDE::Types::Hash
    attribute :reprocessingEfficiency, SDE::Types::Float
    attribute :reprocessingHangarFlag, SDE::Types::Integer
    attribute :reprocessingStationsTake, SDE::Types::Float
    attribute :solarSystemID, SDE::Types::Integer
    attribute :typeID, SDE::Types::Integer
    attribute :useOperationName, SDE::Types::Bool
  end
end
