# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npc_characters.msgpack.gz (11303 entries)

class SDE::NpcCharacter < Dry::Struct
  transform_keys(&:to_sym)

  attribute :agent, SDE::Types::Hash.optional.meta(omittable: true)
  attribute :ancestryID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :bloodlineID, SDE::Types::Integer
  attribute :careerID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :ceo, SDE::Types::Bool
  attribute :corporationID, SDE::Types::Integer
  attribute :description, SDE::Types::String.optional.meta(omittable: true)
  attribute :gender, SDE::Types::Bool
  attribute :locationID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, SDE::Types::LocalizedString
  attribute :raceID, SDE::Types::Integer
  attribute :schoolID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :skills, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  attribute :specialityID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :startDate, SDE::Types::String.optional.meta(omittable: true)
  attribute :uniqueName, SDE::Types::Bool
end
