# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/planet_schematics.msgpack.gz (68 entries)

module SDE
  class PlanetSchematic < Dry::Struct
    transform_keys(&:to_sym)

    attribute :cycleTime, SDE::Types::Integer
    attribute :name, SDE::Types::LocalizedString
    attribute :pins, SDE::Types::Array.of(SDE::Types::Integer)
    attribute :types, SDE::Types::Hash
  end
end
