# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/planet_resources.msgpack.gz (25798 entries)

class SDE::PlanetResource < Dry::Struct
  transform_keys(&:to_sym)

  attribute :power, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :reagent, SDE::Types::Hash.optional.meta(omittable: true)
  attribute :workforce, SDE::Types::Integer.optional.meta(omittable: true)
end
