# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/races.msgpack.gz (11 entries)

module SDE
  class Race < Dry::Struct
    transform_keys(&:to_sym)

    attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, SDE::Types::LocalizedString
    attribute :shipTypeID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :skills, SDE::Types::Hash.optional.meta(omittable: true)
  end
end
