# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/skins.msgpack.gz (6795 entries)

module SDE
  class Skin < Dry::Struct
    transform_keys(&:to_sym)

    attribute :allowCCPDevs, SDE::Types::Bool
    attribute :internalName, SDE::Types::String
    attribute :isStructureSkin, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :skinDescription, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :skinMaterialID, SDE::Types::Integer
    attribute :types, SDE::Types::Array.of(SDE::Types::Integer)
    attribute :visibleSerenity, SDE::Types::Bool
    attribute :visibleTranquility, SDE::Types::Bool
  end
end
