# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/skin_licenses.msgpack.gz (11624 entries)

module SDE
  class SkinLicense < Dry::Struct
    transform_keys(&:to_sym)

    attribute :duration, SDE::Types::Integer
    attribute :isSingleUse, SDE::Types::Bool.optional.meta(omittable: true)
    attribute :licenseTypeID, SDE::Types::Integer
    attribute :skinID, SDE::Types::Integer
  end
end
