# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/skin_materials.msgpack.gz (837 entries)

class SDE::SkinMaterial < Dry::Struct
  transform_keys(&:to_sym)

  attribute :displayName, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :materialSetID, SDE::Types::Integer
end
