# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/sovereignty_upgrades.msgpack.gz (49 entries)

class SDE::SovereigntyUpgrade < Dry::Struct
  transform_keys(&:to_sym)

  attribute :fuel, SDE::Types::Hash.optional.meta(omittable: true)
  attribute :mutually_exclusive_group, SDE::Types::String
  attribute :power_allocation, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :power_production, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :workforce_allocation, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :workforce_production, SDE::Types::Integer.optional.meta(omittable: true)
end
