# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/station_operations.msgpack.gz (66 entries)

module SDE
  class StationOperation < Dry::Struct
    transform_keys(&:to_sym)

    attribute :activityID, SDE::Types::Integer
    attribute :border, SDE::Types::Float
    attribute :corridor, SDE::Types::Float
    attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :fringe, SDE::Types::Float
    attribute :hub, SDE::Types::Float
    attribute :manufacturingFactor, SDE::Types::Float
    attribute :operationName, SDE::Types::LocalizedString
    attribute :ratio, SDE::Types::Float
    attribute :researchFactor, SDE::Types::Float
    attribute :services, SDE::Types::Array.of(SDE::Types::Integer)
    attribute :stationTypes, SDE::Types::Hash.optional.meta(omittable: true)
  end
end
