# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/type_bonus.msgpack.gz (641 entries)

module SDE
  class TypeBonus < Dry::Struct
    transform_keys(&:to_sym)

    attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
    attribute :miscBonuses, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
    attribute :roleBonuses, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
    attribute :types, SDE::Types::Hash.optional.meta(omittable: true)
  end
end
