# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/type_dogma.msgpack.gz (26007 entries)

module SDE
  class TypeDogma < Dry::Struct
    transform_keys(&:to_sym)

    attribute :dogmaAttributes, SDE::Types::Array.of(SDE::Types::Hash)
    attribute :dogmaEffects, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  end
end
