# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/types.msgpack.gz (51135 entries)

class SDE::Type < Dry::Struct
  transform_keys(&:to_sym)

  attribute :basePrice, SDE::Types::Float.optional.meta(omittable: true)
  attribute :capacity, SDE::Types::Float.optional.meta(omittable: true)
  attribute :description, SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :factionID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :graphicID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :groupID, SDE::Types::Integer
  attribute :iconID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :marketGroupID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :mass, SDE::Types::Float.optional.meta(omittable: true)
  attribute :metaGroupID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, SDE::Types::LocalizedString
  attribute :portionSize, SDE::Types::Integer
  attribute :published, SDE::Types::Bool
  attribute :raceID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :radius, SDE::Types::Float.optional.meta(omittable: true)
  attribute :soundID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :variationParentTypeID, SDE::Types::Integer.optional.meta(omittable: true)
  attribute :volume, SDE::Types::Float.optional.meta(omittable: true)
end
