# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/type_materials.msgpack.gz (9485 entries)

class SDE::TypeMaterial < Dry::Struct
  transform_keys(&:to_sym)

  attribute :materials, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
  attribute :randomizedMaterials, SDE::Types::Array.of(SDE::Types::Hash).optional.meta(omittable: true)
end
