# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/agentTypes.marshal.gz (13 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class AgentType < Dry::Struct
    transform_keys(&:to_sym)

    attribute :name, EVE::SDE::Types::String
  end
end
EVE::SDE::AgentType.struct_class = EVE::SDE::Structs::AgentType

