# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/agentsInSpace.marshal.gz (360 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class AgentsInSpace < Dry::Struct
    transform_keys(&:to_sym)

    attribute :dungeonID, EVE::SDE::Types::Integer
    attribute :solarSystemID, EVE::SDE::Types::Integer
    attribute :spawnPointID, EVE::SDE::Types::Integer
    attribute :typeID, EVE::SDE::Types::Integer
  end
end
EVE::SDE::AgentsInSpace.struct_class = EVE::SDE::Structs::AgentsInSpace

