# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/ancestries.msgpack.gz (43 entries)

class EVE::SDE::Ancestry < Dry::Struct
  transform_keys(&:to_sym)

  attribute :bloodlineID, EVE::SDE::Types::Integer
  attribute :charisma, EVE::SDE::Types::Integer
  attribute :description, EVE::SDE::Types::LocalizedString
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :intelligence, EVE::SDE::Types::Integer
  attribute :memory, EVE::SDE::Types::Integer
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :perception, EVE::SDE::Types::Integer
  attribute :shortDescription, EVE::SDE::Types::String.optional.meta(omittable: true)
  attribute :willpower, EVE::SDE::Types::Integer
end
