# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/ancestries.marshal.gz (43 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Ancestry < Dry::Struct
    transform_keys(&:to_sym)

    attribute :bloodlineID, EVE::SDE::Types::Integer
    attribute :charisma, EVE::SDE::Types::Integer
    attribute :description, EVE::SDE::Types::LocalizedString
    attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :intelligence, EVE::SDE::Types::Integer
    attribute :memory, EVE::SDE::Types::Integer
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :perception, EVE::SDE::Types::Integer
    attribute :shortDescription, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :willpower, EVE::SDE::Types::Integer
  end
end
EVE::SDE::Ancestry.struct_class = EVE::SDE::Structs::Ancestry

