# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/bloodlines.msgpack.gz (18 entries)

class EVE::SDE::Bloodline < Dry::Struct
  transform_keys(&:to_sym)

  attribute :charisma, EVE::SDE::Types::Integer
  attribute :corporationID, EVE::SDE::Types::Integer
  attribute :description, EVE::SDE::Types::LocalizedString
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :intelligence, EVE::SDE::Types::Integer
  attribute :memory, EVE::SDE::Types::Integer
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :perception, EVE::SDE::Types::Integer
  attribute :raceID, EVE::SDE::Types::Integer
  attribute :willpower, EVE::SDE::Types::Integer
end
