# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/blueprints.marshal.gz (5059 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::Blueprint < Dry::Struct
  transform_keys(&:to_sym)

  attribute :activities, EVE::SDE::Types::Hash
  attribute :blueprintTypeID, EVE::SDE::Types::Integer
  attribute :maxProductionLimit, EVE::SDE::Types::Integer
end
