# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/categories.marshal.gz (48 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::Category < Dry::Struct
  transform_keys(&:to_sym)

  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :published, EVE::SDE::Types::Bool
end
