# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/certificates.msgpack.gz (136 entries)

class EVE::SDE::Certificate < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::LocalizedString
  attribute :groupID, EVE::SDE::Types::Integer
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :recommendedFor, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :skillTypes, EVE::SDE::Types::Hash
end
