# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/certificates.marshal.gz (136 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Certificate < Dry::Struct
    transform_keys(&:to_sym)

    attribute :description, EVE::SDE::Types::LocalizedString
    attribute :groupID, EVE::SDE::Types::Integer
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :recommendedFor, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
    attribute :skillTypes, EVE::SDE::Types::Hash
  end
end
EVE::SDE::Certificate.struct_class = EVE::SDE::Structs::Certificate

