# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/characterAttributes.marshal.gz (5 entries)

class EVE::SDE::CharacterAttribute < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::String
  attribute :iconID, EVE::SDE::Types::Integer
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :notes, EVE::SDE::Types::String
  attribute :shortDescription, EVE::SDE::Types::String
end
