# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/clone_grades.msgpack.gz (4 entries)

class EVE::SDE::CloneGrade < Dry::Struct
  transform_keys(&:to_sym)

  attribute :name, EVE::SDE::Types::String
  attribute :skills, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash)
end
