# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/cloneGrades.marshal.gz (4 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class CloneGrade < Dry::Struct
    transform_keys(&:to_sym)

    attribute :name, EVE::SDE::Types::String
    attribute :skills, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash)
  end
end
EVE::SDE::CloneGrade.struct_class = EVE::SDE::Structs::CloneGrade

