# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/compressibleTypes.marshal.gz (206 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::CompressibleType < Dry::Struct
  transform_keys(&:to_sym)

  attribute :compressedTypeID, EVE::SDE::Types::Integer
end
