# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/compressibleTypes.marshal.gz (206 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class CompressibleType < Dry::Struct
    transform_keys(&:to_sym)

    attribute :compressedTypeID, EVE::SDE::Types::Integer
  end
end
EVE::SDE::CompressibleType.struct_class = EVE::SDE::Structs::CompressibleType

