# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/control_tower_resources.msgpack.gz (44 entries)

class EVE::SDE::ControlTowerResource < Dry::Struct
  transform_keys(&:to_sym)

  attribute :resources, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash)
end
