# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/controlTowerResources.marshal.gz (44 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class ControlTowerResource < Dry::Struct
    transform_keys(&:to_sym)

    attribute :resources, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash)
  end
end
EVE::SDE::ControlTowerResource.struct_class = EVE::SDE::Structs::ControlTowerResource

