# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/contrabandTypes.marshal.gz (8 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class ContrabandType < Dry::Struct
    transform_keys(&:to_sym)

    attribute :factions, EVE::SDE::Types::Hash
  end
end
EVE::SDE::ContrabandType.struct_class = EVE::SDE::Structs::ContrabandType

