# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/corporationActivities.marshal.gz (20 entries)

class EVE::SDE::CorporationActivity < Dry::Struct
  transform_keys(&:to_sym)

  attribute :name, EVE::SDE::Types::LocalizedString
end
