# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/corporationActivities.marshal.gz (20 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class CorporationActivity < Dry::Struct
    transform_keys(&:to_sym)

    attribute :name, EVE::SDE::Types::LocalizedString
  end
end
EVE::SDE::CorporationActivity.struct_class = EVE::SDE::Structs::CorporationActivity

