# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dbuffCollections.marshal.gz (206 entries)

class EVE::SDE::DbuffCollection < Dry::Struct
  transform_keys(&:to_sym)

  attribute :aggregateMode, EVE::SDE::Types::String
  attribute :developerDescription, EVE::SDE::Types::String
  attribute :displayName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :itemModifiers, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  attribute :locationGroupModifiers, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  attribute :locationModifiers, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  attribute :locationRequiredSkillModifiers, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  attribute :operationName, EVE::SDE::Types::String
  attribute :showOutputValueInUI, EVE::SDE::Types::String
end
