# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogmaUnits.marshal.gz (60 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class DogmaUnit < Dry::Struct
    transform_keys(&:to_sym)

    attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :displayName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::String
  end
end
EVE::SDE::DogmaUnit.struct_class = EVE::SDE::Structs::DogmaUnit

