# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogmaAttributeCategories.marshal.gz (37 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::DogmaAttributeCategory < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::String.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::String
end
