# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogma_effects.msgpack.gz (3354 entries)

class EVE::SDE::DogmaEffect < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :disallowAutoRepeat, EVE::SDE::Types::Bool
  attribute :dischargeAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :displayName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :distribution, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :durationAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :effectCategoryID, EVE::SDE::Types::Integer
  attribute :electronicChance, EVE::SDE::Types::Bool
  attribute :falloffAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :fittingUsageChanceAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :guid, EVE::SDE::Types::String.optional.meta(omittable: true)
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :isAssistance, EVE::SDE::Types::Bool
  attribute :isOffensive, EVE::SDE::Types::Bool
  attribute :isWarpSafe, EVE::SDE::Types::Bool
  attribute :modifierInfo, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::String
  attribute :npcActivationChanceAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :npcUsageChanceAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :propulsionChance, EVE::SDE::Types::Bool
  attribute :published, EVE::SDE::Types::Bool
  attribute :rangeAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :rangeChance, EVE::SDE::Types::Bool
  attribute :resistanceAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :trackingSpeedAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
end
