# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dogmaAttributes.marshal.gz (2822 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class DogmaAttribute < Dry::Struct
    transform_keys(&:to_sym)

    attribute :attributeCategoryID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :chargeRechargeTimeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :dataType, EVE::SDE::Types::Integer
    attribute :defaultValue, EVE::SDE::Types::Float
    attribute :description, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :displayName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :displayWhenZero, EVE::SDE::Types::Bool
    attribute :highIsGood, EVE::SDE::Types::Bool
    attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :maxAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :minAttributeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::String
    attribute :published, EVE::SDE::Types::Bool
    attribute :stackable, EVE::SDE::Types::Bool
    attribute :tooltipDescription, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :tooltipTitle, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :unitID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  end
end
EVE::SDE::DogmaAttribute.struct_class = EVE::SDE::Structs::DogmaAttribute

