# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/dynamicItemAttributes.marshal.gz (413 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class DynamicItemAttribute < Dry::Struct
    transform_keys(&:to_sym)

    attribute :attributeIDs, EVE::SDE::Types::Hash
    attribute :inputOutputMapping, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash)
  end
end
EVE::SDE::DynamicItemAttribute.struct_class = EVE::SDE::Structs::DynamicItemAttribute

