# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/factions.marshal.gz (27 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Faction < Dry::Struct
    transform_keys(&:to_sym)

    attribute :corporationID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :description, EVE::SDE::Types::LocalizedString
    attribute :flatLogo, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :flatLogoWithName, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :iconID, EVE::SDE::Types::Integer
    attribute :memberRaces, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
    attribute :militiaCorporationID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :shortDescription, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :sizeFactor, EVE::SDE::Types::Float
    attribute :solarSystemID, EVE::SDE::Types::Integer
    attribute :uniqueName, EVE::SDE::Types::Bool
  end
end
EVE::SDE::Faction.struct_class = EVE::SDE::Structs::Faction

