# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/freelanceJobSchemas.marshal.gz (1 entries)

class EVE::SDE::FreelanceJobSchema < Dry::Struct
  transform_keys(&:to_sym)

  attribute :BoostShield, EVE::SDE::Types::Hash
  attribute :CaptureFWComplex, EVE::SDE::Types::Hash
  attribute :DamageShip, EVE::SDE::Types::Hash
  attribute :DefendFWComplex, EVE::SDE::Types::Hash
  attribute :DeliverItem, EVE::SDE::Types::Hash
  attribute :KillCapsuleer, EVE::SDE::Types::Hash
  attribute :KillNPC, EVE::SDE::Types::Hash
  attribute :MineOre, EVE::SDE::Types::Hash
  attribute :RepairArmor, EVE::SDE::Types::Hash
  attribute :ShipInsurance, EVE::SDE::Types::Hash
end
