# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/graphics.marshal.gz (5549 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Graphic < Dry::Struct
    transform_keys(&:to_sym)

    attribute :graphicFile, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :iconFolder, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :sofFactionName, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :sofHullName, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :sofLayout, EVE::SDE::Types::Array.of(EVE::SDE::Types::String).optional.meta(omittable: true)
    attribute :sofMaterialSetID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :sofRaceName, EVE::SDE::Types::String.optional.meta(omittable: true)
  end
end
EVE::SDE::Graphic.struct_class = EVE::SDE::Structs::Graphic

