# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/groups.marshal.gz (1578 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Group < Dry::Struct
    transform_keys(&:to_sym)

    attribute :anchorable, EVE::SDE::Types::Bool
    attribute :anchored, EVE::SDE::Types::Bool
    attribute :categoryID, EVE::SDE::Types::Integer
    attribute :fittableNonSingleton, EVE::SDE::Types::Bool
    attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :published, EVE::SDE::Types::Bool
    attribute :useBasePrice, EVE::SDE::Types::Bool
  end
end
EVE::SDE::Group.struct_class = EVE::SDE::Structs::Group

