# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/groups.marshal.gz (1578 entries)

class EVE::SDE::Group < Dry::Struct
  transform_keys(&:to_sym)

  attribute :anchorable, EVE::SDE::Types::Bool
  attribute :anchored, EVE::SDE::Types::Bool
  attribute :categoryID, EVE::SDE::Types::Integer
  attribute :fittableNonSingleton, EVE::SDE::Types::Bool
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :published, EVE::SDE::Types::Bool
  attribute :useBasePrice, EVE::SDE::Types::Bool
end
