# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/icons.marshal.gz (4452 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::Icon < Dry::Struct
  transform_keys(&:to_sym)

  attribute :iconFile, EVE::SDE::Types::String
end
