# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/icons.marshal.gz (4452 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Icon < Dry::Struct
    transform_keys(&:to_sym)

    attribute :iconFile, EVE::SDE::Types::String
  end
end
EVE::SDE::Icon.struct_class = EVE::SDE::Structs::Icon

