# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/landmarks.marshal.gz (45 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Landmark < Dry::Struct
    transform_keys(&:to_sym)

    attribute :description, EVE::SDE::Types::LocalizedString
    attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :locationID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :position, EVE::SDE::Types::Hash
  end
end
EVE::SDE::Landmark.struct_class = EVE::SDE::Structs::Landmark

