# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/mapSolarSystems.marshal.gz (8437 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::MapSolarSystem < Dry::Struct
  transform_keys(&:to_sym)

  attribute :border, EVE::SDE::Types::Bool.optional.meta(omittable: true)
  attribute :constellationID, EVE::SDE::Types::Integer
  attribute :corridor, EVE::SDE::Types::Bool.optional.meta(omittable: true)
  attribute :disallowedAnchorCategories, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :disallowedAnchorGroups, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :factionID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :fringe, EVE::SDE::Types::Bool.optional.meta(omittable: true)
  attribute :hub, EVE::SDE::Types::Bool.optional.meta(omittable: true)
  attribute :international, EVE::SDE::Types::Bool.optional.meta(omittable: true)
  attribute :luminosity, EVE::SDE::Types::Float.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :planetIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :position, EVE::SDE::Types::Hash
  attribute :position2D, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :radius, EVE::SDE::Types::Float
  attribute :regionID, EVE::SDE::Types::Integer
  attribute :regional, EVE::SDE::Types::Bool.optional.meta(omittable: true)
  attribute :securityClass, EVE::SDE::Types::String.optional.meta(omittable: true)
  attribute :securityStatus, EVE::SDE::Types::Float
  attribute :starID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :stargateIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :visualEffect, EVE::SDE::Types::String.optional.meta(omittable: true)
  attribute :wormholeClassID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
end
