# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_stars.msgpack.gz (8036 entries)

class EVE::SDE::MapStar < Dry::Struct
  transform_keys(&:to_sym)

  attribute :radius, EVE::SDE::Types::Integer
  attribute :solarSystemID, EVE::SDE::Types::Integer
  attribute :statistics, EVE::SDE::Types::Hash
  attribute :typeID, EVE::SDE::Types::Integer
end
