# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_planets.msgpack.gz (67961 entries)

class EVE::SDE::MapPlanet < Dry::Struct
  transform_keys(&:to_sym)

  attribute :asteroidBeltIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :attributes, EVE::SDE::Types::Hash
  attribute :celestialIndex, EVE::SDE::Types::Integer
  attribute :moonIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :npcStationIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :orbitID, EVE::SDE::Types::Integer
  attribute :position, EVE::SDE::Types::Hash
  attribute :radius, EVE::SDE::Types::Integer
  attribute :solarSystemID, EVE::SDE::Types::Integer
  attribute :statistics, EVE::SDE::Types::Hash
  attribute :typeID, EVE::SDE::Types::Integer
  attribute :uniqueName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
end
