# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/mapStargates.marshal.gz (13776 entries)

class EVE::SDE::MapStargate < Dry::Struct
  transform_keys(&:to_sym)

  attribute :destination, EVE::SDE::Types::Hash
  attribute :position, EVE::SDE::Types::Hash
  attribute :solarSystemID, EVE::SDE::Types::Integer
  attribute :typeID, EVE::SDE::Types::Integer
end
