# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/mapMoons.marshal.gz (342170 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::MapMoon < Dry::Struct
  transform_keys(&:to_sym)

  attribute :attributes, EVE::SDE::Types::Hash
  attribute :celestialIndex, EVE::SDE::Types::Integer
  attribute :npcStationIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :orbitID, EVE::SDE::Types::Integer
  attribute :orbitIndex, EVE::SDE::Types::Integer
  attribute :position, EVE::SDE::Types::Hash
  attribute :radius, EVE::SDE::Types::Float
  attribute :solarSystemID, EVE::SDE::Types::Integer
  attribute :statistics, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :typeID, EVE::SDE::Types::Integer
  attribute :uniqueName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
end
