# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/mapConstellations.marshal.gz (1175 entries)

class EVE::SDE::MapConstellation < Dry::Struct
  transform_keys(&:to_sym)

  attribute :factionID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :position, EVE::SDE::Types::Hash
  attribute :regionID, EVE::SDE::Types::Integer
  attribute :solarSystemIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
  attribute :wormholeClassID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
end
