# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/map_asteroid_belts.msgpack.gz (40928 entries)

class EVE::SDE::MapAsteroidBelt < Dry::Struct
  transform_keys(&:to_sym)

  attribute :celestialIndex, EVE::SDE::Types::Integer
  attribute :orbitID, EVE::SDE::Types::Integer
  attribute :orbitIndex, EVE::SDE::Types::Integer
  attribute :position, EVE::SDE::Types::Hash
  attribute :radius, EVE::SDE::Types::Float.optional.meta(omittable: true)
  attribute :solarSystemID, EVE::SDE::Types::Integer
  attribute :statistics, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :typeID, EVE::SDE::Types::Integer
  attribute :uniqueName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
end
