# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/mapRegions.marshal.gz (113 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class MapRegion < Dry::Struct
    transform_keys(&:to_sym)

    attribute :constellationIDs, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
    attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :factionID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :nebulaID, EVE::SDE::Types::Integer
    attribute :position, EVE::SDE::Types::Hash
    attribute :wormholeClassID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  end
end
EVE::SDE::MapRegion.struct_class = EVE::SDE::Structs::MapRegion

