# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/mapStars.marshal.gz (8036 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class MapStar < Dry::Struct
    transform_keys(&:to_sym)

    attribute :radius, EVE::SDE::Types::Integer
    attribute :solarSystemID, EVE::SDE::Types::Integer
    attribute :statistics, EVE::SDE::Types::Hash
    attribute :typeID, EVE::SDE::Types::Integer
  end
end
EVE::SDE::MapStar.struct_class = EVE::SDE::Structs::MapStar

