# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/marketGroups.marshal.gz (2092 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::MarketGroup < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :hasTypes, EVE::SDE::Types::Bool
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :parentGroupID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
end
