# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/masteries.marshal.gz (468 entries)

class EVE::SDE::Mastery < Dry::Struct
  transform_keys(&:to_sym)

  attribute :"0", EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
  attribute :"1", EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
  attribute :"2", EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
  attribute :"3", EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
  attribute :"4", EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
end
