# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/meta_groups.msgpack.gz (13 entries)

class EVE::SDE::MetaGroup < Dry::Struct
  transform_keys(&:to_sym)

  attribute :color, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :iconSuffix, EVE::SDE::Types::String.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::LocalizedString
end
