# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npcCorporations.marshal.gz (283 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::NpcCorporation < Dry::Struct
  transform_keys(&:to_sym)

  attribute :allowedMemberRaces, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :ceoID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :corporationTrades, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :deleted, EVE::SDE::Types::Bool
  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :divisions, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :enemyID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :exchangeRates, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :extent, EVE::SDE::Types::String
  attribute :factionID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :friendID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :hasPlayerPersonnelManager, EVE::SDE::Types::Bool
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :initialPrice, EVE::SDE::Types::Integer
  attribute :investors, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :lpOfferTables, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer).optional.meta(omittable: true)
  attribute :mainActivityID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :memberLimit, EVE::SDE::Types::Integer
  attribute :minSecurity, EVE::SDE::Types::Float
  attribute :minimumJoinStanding, EVE::SDE::Types::Integer
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :raceID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :secondaryActivityID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :sendCharTerminationMessage, EVE::SDE::Types::Bool
  attribute :shares, EVE::SDE::Types::Integer
  attribute :size, EVE::SDE::Types::String
  attribute :sizeFactor, EVE::SDE::Types::Float.optional.meta(omittable: true)
  attribute :solarSystemID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :stationID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :taxRate, EVE::SDE::Types::Float
  attribute :tickerName, EVE::SDE::Types::String
  attribute :uniqueName, EVE::SDE::Types::Bool
end
