# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npcStations.marshal.gz (5154 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::NpcStation < Dry::Struct
  transform_keys(&:to_sym)

  attribute :celestialIndex, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :operationID, EVE::SDE::Types::Integer
  attribute :orbitID, EVE::SDE::Types::Integer
  attribute :orbitIndex, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :ownerID, EVE::SDE::Types::Integer
  attribute :position, EVE::SDE::Types::Hash
  attribute :reprocessingEfficiency, EVE::SDE::Types::Float
  attribute :reprocessingHangarFlag, EVE::SDE::Types::Integer
  attribute :reprocessingStationsTake, EVE::SDE::Types::Float
  attribute :solarSystemID, EVE::SDE::Types::Integer
  attribute :typeID, EVE::SDE::Types::Integer
  attribute :useOperationName, EVE::SDE::Types::Bool
end
