# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npc_corporation_divisions.msgpack.gz (10 entries)

class EVE::SDE::NpcCorporationDivision < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :displayName, EVE::SDE::Types::String.optional.meta(omittable: true)
  attribute :internalName, EVE::SDE::Types::String
  attribute :leaderTypeName, EVE::SDE::Types::LocalizedString
  attribute :name, EVE::SDE::Types::LocalizedString
end
