# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/npcCharacters.marshal.gz (11303 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class NpcCharacter < Dry::Struct
    transform_keys(&:to_sym)

    attribute :agent, EVE::SDE::Types::Hash.optional.meta(omittable: true)
    attribute :ancestryID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :bloodlineID, EVE::SDE::Types::Integer
    attribute :careerID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :ceo, EVE::SDE::Types::Bool
    attribute :corporationID, EVE::SDE::Types::Integer
    attribute :description, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :gender, EVE::SDE::Types::Bool
    attribute :locationID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :raceID, EVE::SDE::Types::Integer
    attribute :schoolID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :skills, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
    attribute :specialityID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :startDate, EVE::SDE::Types::String.optional.meta(omittable: true)
    attribute :uniqueName, EVE::SDE::Types::Bool
  end
end
EVE::SDE::NpcCharacter.struct_class = EVE::SDE::Structs::NpcCharacter

