# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/planetResources.marshal.gz (25798 entries)

class EVE::SDE::PlanetResource < Dry::Struct
  transform_keys(&:to_sym)

  attribute :power, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :reagent, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :workforce, EVE::SDE::Types::Integer.optional.meta(omittable: true)
end
