# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/planet_schematics.msgpack.gz (68 entries)

class EVE::SDE::PlanetSchematic < Dry::Struct
  transform_keys(&:to_sym)

  attribute :cycleTime, EVE::SDE::Types::Integer
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :pins, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
  attribute :types, EVE::SDE::Types::Hash
end
