# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/planetSchematics.marshal.gz (68 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class PlanetSchematic < Dry::Struct
    transform_keys(&:to_sym)

    attribute :cycleTime, EVE::SDE::Types::Integer
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :pins, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
    attribute :types, EVE::SDE::Types::Hash
  end
end
EVE::SDE::PlanetSchematic.struct_class = EVE::SDE::Structs::PlanetSchematic

