# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/planetResources.marshal.gz (25798 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class PlanetResource < Dry::Struct
    transform_keys(&:to_sym)

    attribute :power, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :reagent, EVE::SDE::Types::Hash.optional.meta(omittable: true)
    attribute :workforce, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  end
end
EVE::SDE::PlanetResource.struct_class = EVE::SDE::Structs::PlanetResource

