# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/races.marshal.gz (11 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Race < Dry::Struct
    transform_keys(&:to_sym)

    attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :name, EVE::SDE::Types::LocalizedString
    attribute :shipTypeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :skills, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  end
end
EVE::SDE::Race.struct_class = EVE::SDE::Structs::Race

