# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/skinMaterials.marshal.gz (837 entries)

class EVE::SDE::SkinMaterial < Dry::Struct
  transform_keys(&:to_sym)

  attribute :displayName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :materialSetID, EVE::SDE::Types::Integer
end
