# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/skinLicenses.marshal.gz (11624 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class SkinLicense < Dry::Struct
    transform_keys(&:to_sym)

    attribute :duration, EVE::SDE::Types::Integer
    attribute :isSingleUse, EVE::SDE::Types::Bool.optional.meta(omittable: true)
    attribute :licenseTypeID, EVE::SDE::Types::Integer
    attribute :skinID, EVE::SDE::Types::Integer
  end
end
EVE::SDE::SkinLicense.struct_class = EVE::SDE::Structs::SkinLicense

