# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/skins.marshal.gz (6795 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class Skin < Dry::Struct
    transform_keys(&:to_sym)

    attribute :allowCCPDevs, EVE::SDE::Types::Bool
    attribute :internalName, EVE::SDE::Types::String
    attribute :isStructureSkin, EVE::SDE::Types::Bool.optional.meta(omittable: true)
    attribute :skinDescription, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :skinMaterialID, EVE::SDE::Types::Integer
    attribute :types, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
    attribute :visibleSerenity, EVE::SDE::Types::Bool
    attribute :visibleTranquility, EVE::SDE::Types::Bool
  end
end
EVE::SDE::Skin.struct_class = EVE::SDE::Structs::Skin

