# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/skinMaterials.marshal.gz (837 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class SkinMaterial < Dry::Struct
    transform_keys(&:to_sym)

    attribute :displayName, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :materialSetID, EVE::SDE::Types::Integer
  end
end
EVE::SDE::SkinMaterial.struct_class = EVE::SDE::Structs::SkinMaterial

