# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/sovereigntyUpgrades.marshal.gz (49 entries)

class EVE::SDE::SovereigntyUpgrade < Dry::Struct
  transform_keys(&:to_sym)

  attribute :fuel, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  attribute :mutually_exclusive_group, EVE::SDE::Types::String
  attribute :power_allocation, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :power_production, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :workforce_allocation, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :workforce_production, EVE::SDE::Types::Integer.optional.meta(omittable: true)
end
