# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/station_services.msgpack.gz (27 entries)

class EVE::SDE::StationService < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :serviceName, EVE::SDE::Types::LocalizedString
end
