# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/stationOperations.marshal.gz (66 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class StationOperation < Dry::Struct
    transform_keys(&:to_sym)

    attribute :activityID, EVE::SDE::Types::Integer
    attribute :border, EVE::SDE::Types::Float
    attribute :corridor, EVE::SDE::Types::Float
    attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :fringe, EVE::SDE::Types::Float
    attribute :hub, EVE::SDE::Types::Float
    attribute :manufacturingFactor, EVE::SDE::Types::Float
    attribute :operationName, EVE::SDE::Types::LocalizedString
    attribute :ratio, EVE::SDE::Types::Float
    attribute :researchFactor, EVE::SDE::Types::Float
    attribute :services, EVE::SDE::Types::Array.of(EVE::SDE::Types::Integer)
    attribute :stationTypes, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  end
end
EVE::SDE::StationOperation.struct_class = EVE::SDE::Structs::StationOperation

