# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/stationServices.marshal.gz (27 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class StationService < Dry::Struct
    transform_keys(&:to_sym)

    attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
    attribute :serviceName, EVE::SDE::Types::LocalizedString
  end
end
EVE::SDE::StationService.struct_class = EVE::SDE::Structs::StationService

