# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/stationServices.marshal.gz (27 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::StationService < Dry::Struct
  transform_keys(&:to_sym)

  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :serviceName, EVE::SDE::Types::LocalizedString
end
