# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/typeMaterials.marshal.gz (9485 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class TypeMaterial < Dry::Struct
    transform_keys(&:to_sym)

    attribute :materials, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
    attribute :randomizedMaterials, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  end
end
EVE::SDE::TypeMaterial.struct_class = EVE::SDE::Structs::TypeMaterial

