# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/typeDogma.marshal.gz (26007 entries)

require "dry-struct"
require_relative "../types"

class EVE::SDE::TypeDogma < Dry::Struct
  transform_keys(&:to_sym)

  attribute :dogmaAttributes, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash)
  attribute :dogmaEffects, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
end
