# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/typeBonus.marshal.gz (641 entries)

require "dry-struct"
require_relative "../types"

module EVE::SDE::Structs
  class TypeBonus < Dry::Struct
    transform_keys(&:to_sym)

    attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
    attribute :miscBonuses, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
    attribute :roleBonuses, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
    attribute :types, EVE::SDE::Types::Hash.optional.meta(omittable: true)
  end
end
EVE::SDE::TypeBonus.struct_class = EVE::SDE::Structs::TypeBonus

