# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/type_bonus.msgpack.gz (641 entries)

class EVE::SDE::TypeBonus < Dry::Struct
  transform_keys(&:to_sym)

  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :miscBonuses, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  attribute :roleBonuses, EVE::SDE::Types::Array.of(EVE::SDE::Types::Hash).optional.meta(omittable: true)
  attribute :types, EVE::SDE::Types::Hash.optional.meta(omittable: true)
end
