# frozen_string_literal: true

# Auto-generated by rake sde:generate_structs
# Source: sde/types.msgpack.gz (51135 entries)

class EVE::SDE::Type < Dry::Struct
  transform_keys(&:to_sym)

  attribute :basePrice, EVE::SDE::Types::Float.optional.meta(omittable: true)
  attribute :capacity, EVE::SDE::Types::Float.optional.meta(omittable: true)
  attribute :description, EVE::SDE::Types::LocalizedString.optional.meta(omittable: true)
  attribute :factionID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :graphicID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :groupID, EVE::SDE::Types::Integer
  attribute :iconID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :marketGroupID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :mass, EVE::SDE::Types::Float.optional.meta(omittable: true)
  attribute :metaGroupID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :name, EVE::SDE::Types::LocalizedString
  attribute :portionSize, EVE::SDE::Types::Integer
  attribute :published, EVE::SDE::Types::Bool
  attribute :raceID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :radius, EVE::SDE::Types::Float.optional.meta(omittable: true)
  attribute :soundID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :variationParentTypeID, EVE::SDE::Types::Integer.optional.meta(omittable: true)
  attribute :volume, EVE::SDE::Types::Float.optional.meta(omittable: true)
end
